### ISSUE TITLE
suggestion: better border-box reset?

### ISSUE THREAD

**Issue by Offirmo** [mike-engel/a11y-css-reset#10]
Just a small contribution.

I checked your nice lib and found this:
https://github.com/mike-engel/a11y-css-reset/blob/13fa26d0fa978443c83c624f518f7438f0b0565c/reset.css#L4

About setting border-box everywhere, I heard about this technique which I believe is superior:

```css
/* apply a natural box layout model to all elements, but allowing components to change
 * https://www.paulirish.com/2012/box-sizing-border-box-ftw/
 */
html                 { box-sizing: border-box; }
*, *:before, *:after { box-sizing: inherit; }
```

The rationale is that it allows to opt-out easily if needed.
